name: StandPlace
version: @version@
main: com.bun133.standplace.Standplace
api-version: 1.15
authors: [ Bun133 ]
description: The each players have own stand to replace under block to specific block
website: https://twitter.com/bun133_
command:
  st:
    destcription: StandPlaceCommand
    permission: op
    permission-message: You don't have enough Perm!
    usase: /<command> <s/e>